import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { CssBaseline } from '@mui/material'
import brickWall from '@/assets/images/bricks.jpg'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CssBaseline />
        {children}
        <div style={{
            backgroundImage: `url(${brickWall.src})`,
            position: 'fixed',
            zIndex: '-99',
            width: '100%',
            height: '100%',
            top:0
        }} />
        </body>
        </html>
    )
}
